/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/s5GntSPNqTk
 */
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useRouter } from "next/navigation"
import { Appointments, Clients } from "@/types/types"

export function FormUI() {
    const router = useRouter()
    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault()
        const formData = new FormData(e.target as HTMLFormElement)
        let fn = formData.get("first-name")
        let ln = formData.get("last-name")
        let loc = formData.get("location")
        let date = formData.get("appointment-date")
        let time = formData.get("appointment-time")
        let appontment: Appointments = {
            id: randId(),
            Date: date as string,
            Time: time as string,
        }
        let client: Clients = {
            id: randId(),
            FirstName: fn as string,
            LastName: ln as string,
            Location: loc as string,
            Appointments: [appontment]
        }

        const fetchClients = async (client: Clients) => {
            const res = await fetch("/api/newclient", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify(client)
            })
            const data = await res.json()
            console.log(data)
        }
        fetchClients(client)
        console.log("Form submitted")
        router.push("/")
    }
    const randId = () => {
        return Math.random().toString(36).substr(2, 9);
    }

    return (
        <div className="max-w-md mx-auto space-y-6">
            <div className="text-center space-y-2">
                <h1 className="text-3xl font-bold">Appointment Form</h1>
                <p className="text-gray-500 dark:text-gray-400">Fill in your details to schedule an appointment</p>
            </div>
            <Card>
                <form onSubmit={handleSubmit}>
                    <CardHeader>
                        <CardTitle>Appointment Details</CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label htmlFor="first-name">First name</Label>
                                <Input id="first-name" name="first-name" placeholder="John" required />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="last-name">Last name</Label>
                                <Input id="last-name" name="last-name" placeholder="Doe" required />
                            </div>
                        </div>
                        <div className="space-y-2">
                            <Label htmlFor="location">Location</Label>
                            <Input id="location" name="location" placeholder="New York" required />
                        </div>
                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label htmlFor="appointment-date">Appointment Date</Label>
                                <Input id="appointment-date" name="appointment-date" required type="date" />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="appointment-time">Appointment Time</Label>
                                <Input id="appointment-time" name="appointment-time" required type="time" />
                            </div>
                        </div>
                    </CardContent>
                    <CardFooter>
                        <Button className="w-full" type="submit">
                            Save Appointment
                        </Button>
                    </CardFooter>
                </form>
            </Card>
        </div >
    )
}
