/**
import { Navbar } from '@/components/navbar'
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6tT3mdJXvSI
 */
import Link from "next/link"
import { NavigationMenuLink, NavigationMenuList, NavigationMenu } from "@/components/ui/navigation-menu"

export function Navbar() {
    return (
        <header className="flex h-20 w-full shrink-0 items-center px-4 md:px-6">
            <Link className="mr-6 flex" href="/">
                <PersonStandingIcon className="h-6 w-6" />
                <span className="sr-only">FitTrack Inc</span>
            </Link>
            <NavigationMenu className="flex">
                <NavigationMenuList>
                    <NavigationMenuLink asChild>
                        <Link
                            className="text-white group inline-flex h-9 w-max items-center justify-center rounded-md  px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 bg-black"
                            href="/"
                        >
                            Home
                        </Link>
                    </NavigationMenuLink>
                </NavigationMenuList>
            </NavigationMenu>
            <div className="ml-auto">
                <NavigationMenu className="flex">
                    <NavigationMenuList>
                        <NavigationMenuLink asChild>
                            <Link
                                className="text-white group inline-flex h-9 w-max items-center justify-center rounded-md bg-black px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
                                href="/addclient"
                            >
                                Add new client
                            </Link>
                        </NavigationMenuLink>
                    </NavigationMenuList>
                </NavigationMenu>
            </div>
        </header>
    )
}


function PersonStandingIcon(props: any) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <circle cx="12" cy="5" r="1" />
            <path d="m9 20 3-6 3 6" />
            <path d="m6 8 6 2 6-2" />
            <path d="M12 10v4" />
        </svg>
    )
}
